### ISSUE TITLE
I keep getting Error deep recursion: expected logic got rich_narcissist_nonsense make_me_great.rb:1-∞  

### ISSUE THREAD

**Issue by wadestuart** [rickr/trumpify#4]
I have tried to read the documentation,  but it seems very light and every time I refresh it seems to change.

**Comment by rickr** [comment]
Every things looks fine to me. Maybe your small hands made a typo?

**Comment by wadestuart** [comment]
I verified my hands are larger than average see screenshot.  I think this needs to be a new feature,  perhaps we could build some sort of physical ingress/egress blocking structure between the library and all of the dirty data  -- I am sure if we optimize it most of the creation cost could be placed on some other library?

![average_hands.jpg](https://cloud.githubusercontent.com/assets/10146102/16747493/f3cf665e-4784-11e6-8edc-80ec4e53574d.jpg)
